baseurl = "https://www.jmbit.de/"
languageCode = "de-de"
theme = "terminal"
#paginate = 5
defaultContentLanguage= "de"

[params]
  contentTypeName = "blog"
  themeColor = "blue"
  showMenuItems = 5
  fullWidthTheme = false
  centerTheme = true 

[languages]
  [languages.de]
	 [languages.de.params]
      title = "Johannes Bülow IT Consulting"
      subtitle = "Consulting & Support zu IT-Sicherheit, Linux, Hosting, Entwicklung und mehr"
      keywords = "linux, it, consulting, security, hosting, development, jmbit, johannes bülow"
      copyright = "Johannes Bülow"
      menuMore = "Mehr anzeigen"
      readMore = "Weiterlesen"
      readOtherPosts = "Weitere Artikel"
  	   owner = "Johannes Bülow"

    [languages.de.params.logo]
      logoText = "JMB IT"
      logoHomeLink = "/"

    [languages.de.menu]
      [[languages.de.menu.main]]
        identifier = "about"
        name = "Über mich"
        url = "/about/"
      [[languages.de.menu.main]]
        identifier = "Expertise"
        name = "Expertise"
        url = "/expertise.html"     
		[[languages.de.menu.main]]
        identifier = "consulting"
        name = "Consulting"
        url = "/consulting/"
		[[languages.de.menu.main]]
        identifier = "tools"
        name = "Tools"
        url = "/tools/"
		[[languages.de.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog/"
